import NavBar from "@/components/Navigation/NavBar"
import SideBar from "@/components/Navigation/SideBar"

export const metadata = {
    title: 'Search',
    description: 'Generated by create next app',
}



export default function HomeLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            <main>
                <div>{children}</div>
            </main>
        </section>
    )
}
