

export const metadata = {
    title: 'Create',
    description: 'Generated by create next app',
}

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section>
                {children}
        </section>
    )
}
