

export const metadata = {
    title: 'Create',
    description: 'Generated by create next app',
}

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            <div className='flex items-center flex-col gap-5 w-[450px] mx-auto my-0'>
                {children}
            </div>
        </section>
    )
}
