import styles from '../../styles/forms.module.scss'

export const metadata = {
    title: 'Registation',
    description: 'Generated by create next app',
}

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <header className={`flex items-center justify-center h-20 bg-white border-b-[1px] border-solid border-b-[#D9DADC]`}>
                <h1 className="font-bold text-2xl">Van Halen Wave</h1>
            </header>
            <section className={styles.formSection}>
                {children}
            </section>
        </>
    )
}
