import { Inter } from 'next/font/google'
import Providers from '@/components/Providers'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'VH Wave',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Van_Halen_logo.svg/1280px-Van_Halen_logo.svg.png" />
      </head>
      <body className={inter.className}>
        <main>
          <div className=''>
            <Providers>
              {children}
            </Providers>
          </div>
        </main>
      </body>
    </html>
  )
}
