import NavBar from "@/components/NavBar"
import SideBar from "@/components/SideBar"

export const metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

export default function HomeLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            <main>
                <SideBar/>
                <NavBar/>
                <div className="ml-[241px]">{children}</div>
            </main>
        </section>
    )
}
