import NavBar from "@/components/Navigation/NavBar"
import SideBar from "@/components/Navigation/SideBar"
import Player from "@/components/Player/Player"

export const metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

export default function HomeLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            <main>
                <SideBar/>
                <div className="sticky top-0"><NavBar/></div>
                <div className="ml-[241px]">{children}</div>
                <Player />
            </main>
        </section>
    )
}
